---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ancalagon-black
  namespace: traefik-external
spec:
  secretName: ancalagon-black-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.ancalagon.black"
  dnsNames:
    - "ancalagon.black"
    - "*.ancalagon.black"
